### ISSUE TITLE
请问：由u.data分割生成的u[1-5].base和u[1-5].test在哪里有使用？

### ISSUE THREAD

**Issue by jifeer** [HongZhaoHua/jstarcraft-example#1]
![image](https://user-images.githubusercontent.com/9289665/84752962-068b6800-aff1-11ea-95f4-d3e96503d7f0.png)

**Comment by HongZhaoHua** [comment]
没有使用，只是ml-100k数据集自带切分好，用于模型训练和评估时用的。
