### ISSUE TITLE
jstarcraft-example启动报错

### ISSUE THREAD

**Issue by huajia1015** [HongZhaoHua/jstarcraft-example#2]
按照JStarCraft Example的README.md执行，在mac os的terminal终端下运行，启动时报错，如下图所示，错误日志见附件：
[启动日志](![image](https://user-images.githubusercontent.com/7426201/86315815-cb7a6d00-bc5d-11ea-94c7-e1a4e1b41121.png))

**Comment by HongZhaoHua** [comment]
我看了你的错误日志，似乎是JavaCPP和环境冲突或者不兼容导致的。
我本身没有MacOS的测试环境，你是否通过本地maven自动拉取依赖？

可能是终端运行的时候，JavaCPP调用或者拉取的依赖与操作系统不一致或者不兼容导致的。

**Comment by HongZhaoHua** [comment]
或者你终端的资源（内存）不足以启动JavaCPP。
